'use strict';

/**
 * V1 creation diagnostic test matrix — single source of truth for Dev Integrations.
 * Phases 4–5 (gtm/googleAds creation diagnostics services) must execute these steps in order.
 *
 * @see dev-tools/backend/lib/dev/creationDiagnosticsMatrix.js — accessors and validation
 */

const CREATION_DIAGNOSTIC_MATRIX_VERSION = 'v1';

/** Providers covered by the V1 creation diagnostic matrix (GBP excluded — read-only discovery). */
const CREATION_DIAGNOSTIC_PROVIDERS = Object.freeze(['google_ads', 'gtm']);

/**
 * Google Ads V1 creation checklist — 13 plan items, 17 executable steps.
 * Campaign budget uses STANDARD delivery only; campaigns and ads default to PAUSED (enforced in Phase 5).
 */
const GOOGLE_ADS_CREATION_DIAGNOSTIC_STEPS = Object.freeze(
  [
    {
      id: 'campaign_budget',
      order: 1,
      label: 'Campaign Budget',
      description: 'Create a dedicated campaign budget with STANDARD delivery (not ACCELERATED).',
      provider: 'google_ads',
      resourceType: 'ads_campaign_budget',
      action: 'create_campaign_budget',
      group: 'campaign_structure',
      required: true,
      skipWhen: null,
      prerequisites: [],
    },
    {
      id: 'search_campaign',
      order: 2,
      label: 'Search Campaign',
      description: 'Create a paused Search campaign bound to the diagnostic budget.',
      provider: 'google_ads',
      resourceType: 'ads_campaign',
      action: 'create_search_campaign',
      group: 'campaign_structure',
      required: true,
      skipWhen: null,
      prerequisites: ['campaign_budget'],
    },
    {
      id: 'location_targeting',
      order: 3,
      label: 'Location Targeting',
      description: 'Attach at least one location criterion to the diagnostic campaign.',
      provider: 'google_ads',
      resourceType: 'ads_campaign_criterion',
      action: 'attach_location_targeting',
      group: 'campaign_structure',
      required: true,
      skipWhen: null,
      prerequisites: ['search_campaign'],
    },
    {
      id: 'language_targeting',
      order: 4,
      label: 'Language Targeting',
      description: 'Attach at least one language criterion to the diagnostic campaign.',
      provider: 'google_ads',
      resourceType: 'ads_campaign_criterion',
      action: 'attach_language_targeting',
      group: 'campaign_structure',
      required: true,
      skipWhen: null,
      prerequisites: ['search_campaign'],
    },
    {
      id: 'ad_schedule',
      order: 5,
      label: 'Ad Schedule',
      description: 'Attach an ad schedule criterion to the diagnostic campaign.',
      provider: 'google_ads',
      resourceType: 'ads_campaign_criterion',
      action: 'attach_ad_schedule',
      group: 'campaign_structure',
      required: true,
      skipWhen: null,
      prerequisites: ['search_campaign'],
    },
    {
      id: 'ad_group',
      order: 6,
      label: 'Ad Group',
      description: 'Create a paused ad group under the diagnostic campaign.',
      provider: 'google_ads',
      resourceType: 'ads_ad_group',
      action: 'create_ad_group',
      group: 'campaign_structure',
      required: true,
      skipWhen: null,
      prerequisites: ['search_campaign'],
    },
    {
      id: 'responsive_search_ad',
      order: 7,
      label: 'Responsive Search Ad',
      description: 'Create a paused responsive search ad with test copy and a final URL.',
      provider: 'google_ads',
      resourceType: 'ads_ad',
      action: 'create_responsive_search_ad',
      group: 'ads_and_keywords',
      required: true,
      skipWhen: null,
      prerequisites: ['ad_group'],
    },
    {
      id: 'keyword_broad',
      order: 8,
      label: 'Keyword (Broad Match)',
      description: 'Add a broad-match keyword to the diagnostic ad group.',
      provider: 'google_ads',
      resourceType: 'ads_keyword',
      action: 'add_keyword_broad',
      group: 'ads_and_keywords',
      required: true,
      skipWhen: null,
      prerequisites: ['ad_group'],
    },
    {
      id: 'keyword_phrase',
      order: 9,
      label: 'Keyword (Phrase Match)',
      description: 'Add a phrase-match keyword to the diagnostic ad group.',
      provider: 'google_ads',
      resourceType: 'ads_keyword',
      action: 'add_keyword_phrase',
      group: 'ads_and_keywords',
      required: true,
      skipWhen: null,
      prerequisites: ['ad_group'],
    },
    {
      id: 'keyword_exact',
      order: 10,
      label: 'Keyword (Exact Match)',
      description: 'Add an exact-match keyword to the diagnostic ad group.',
      provider: 'google_ads',
      resourceType: 'ads_keyword',
      action: 'add_keyword_exact',
      group: 'ads_and_keywords',
      required: true,
      skipWhen: null,
      prerequisites: ['ad_group'],
    },
    {
      id: 'conversion_action',
      order: 11,
      label: 'Conversion Action',
      description: 'Create a website conversion action for diagnostic measurement.',
      provider: 'google_ads',
      resourceType: 'ads_conversion_action',
      action: 'create_conversion_action',
      group: 'measurement',
      required: true,
      skipWhen: null,
      prerequisites: ['search_campaign'],
    },
    {
      id: 'asset_sitelink',
      order: 12,
      label: 'Sitelink Asset',
      description: 'Create a sitelink extension asset linked to the diagnostic campaign.',
      provider: 'google_ads',
      resourceType: 'ads_asset_sitelink',
      action: 'create_sitelink_asset',
      group: 'extensions',
      required: true,
      skipWhen: null,
      prerequisites: ['search_campaign'],
    },
    {
      id: 'asset_callout',
      order: 13,
      label: 'Callout Asset',
      description: 'Create a callout extension asset linked to the diagnostic campaign.',
      provider: 'google_ads',
      resourceType: 'ads_asset_callout',
      action: 'create_callout_asset',
      group: 'extensions',
      required: true,
      skipWhen: null,
      prerequisites: ['search_campaign'],
    },
    {
      id: 'asset_call',
      order: 14,
      label: 'Call Asset',
      description: 'Create a call extension when a business phone number is available.',
      provider: 'google_ads',
      resourceType: 'ads_asset_call',
      action: 'create_call_asset',
      group: 'extensions',
      required: false,
      skipWhen: 'No business phone number available.',
      prerequisites: ['search_campaign'],
    },
    {
      id: 'remarketing_user_list',
      order: 15,
      label: 'Remarketing / User List',
      description: 'Create a remarketing user list when the account supports it.',
      provider: 'google_ads',
      resourceType: 'ads_remarketing_list',
      action: 'create_remarketing_user_list',
      group: 'audiences',
      required: false,
      skipWhen: 'Account does not support remarketing user lists.',
      prerequisites: ['search_campaign'],
    },
    {
      id: 'negative_keyword_list',
      order: 16,
      label: 'Negative Keyword List',
      description: 'Create a shared negative keyword list for the diagnostic customer.',
      provider: 'google_ads',
      resourceType: 'ads_negative_keyword_list',
      action: 'create_negative_keyword_list',
      group: 'audiences',
      required: true,
      skipWhen: null,
      prerequisites: ['search_campaign'],
    },
    {
      id: 'offline_conversion_import_dry_run',
      order: 17,
      label: 'Offline Conversion Import (Dry Run)',
      description:
        'Validate offline conversion import readiness without uploading real conversions or GCLIDs.',
      provider: 'google_ads',
      resourceType: 'ads_offline_conversion_import',
      action: 'validate_offline_conversion_import',
      group: 'measurement',
      required: true,
      skipWhen: null,
      prerequisites: ['conversion_action'],
    },
  ].map((step) => Object.freeze(step))
);

/**
 * GTM V1 creation checklist — 10 plan items, 10 executable steps.
 * GTM accounts cannot be created via API; container step only runs when none is connected.
 */
const GTM_CREATION_DIAGNOSTIC_STEPS = Object.freeze(
  [
    {
      id: 'container',
      order: 1,
      label: 'Container',
      description:
        'Use the connected container or create one under the existing GTM account when none exists.',
      provider: 'gtm',
      resourceType: 'gtm_container',
      action: 'ensure_container',
      group: 'container_setup',
      required: true,
      skipWhen: 'Usable container already connected.',
      prerequisites: [],
    },
    {
      id: 'workspace',
      order: 2,
      label: 'Workspace',
      description: 'Create or resolve a workspace for diagnostic tag/trigger/variable edits.',
      provider: 'gtm',
      resourceType: 'gtm_workspace',
      action: 'create_workspace',
      group: 'container_setup',
      required: true,
      skipWhen: null,
      prerequisites: ['container'],
    },
    {
      id: 'builtin_variables',
      order: 3,
      label: 'Built-in Variables',
      description: 'Enable required built-in variables (page URL, click, and form signals).',
      provider: 'gtm',
      resourceType: 'gtm_builtin_variable',
      action: 'enable_builtin_variables',
      group: 'variables',
      required: true,
      skipWhen: null,
      prerequisites: ['workspace'],
    },
    {
      id: 'data_layer_variable',
      order: 4,
      label: 'Data Layer Variable',
      description: 'Create a data layer variable (e.g. zug_conversion_value).',
      provider: 'gtm',
      resourceType: 'gtm_variable',
      action: 'create_data_layer_variable',
      group: 'variables',
      required: true,
      skipWhen: null,
      prerequisites: ['workspace'],
    },
    {
      id: 'page_view_trigger',
      order: 5,
      label: 'Page View Trigger',
      description: 'Create a page view trigger for diagnostic tagging.',
      provider: 'gtm',
      resourceType: 'gtm_trigger',
      action: 'create_page_view_trigger',
      group: 'triggers',
      required: true,
      skipWhen: null,
      prerequisites: ['workspace'],
    },
    {
      id: 'custom_event_trigger',
      order: 6,
      label: 'Custom Event Trigger',
      description: 'Create a custom event trigger (e.g. zuggernaut_conversion).',
      provider: 'gtm',
      resourceType: 'gtm_trigger',
      action: 'create_custom_event_trigger',
      group: 'triggers',
      required: true,
      skipWhen: null,
      prerequisites: ['workspace'],
    },
    {
      id: 'ga4_config_tag',
      order: 7,
      label: 'GA4 Config / Google Tag',
      description: 'Create a GA4 configuration tag when a measurement ID is available.',
      provider: 'gtm',
      resourceType: 'gtm_tag',
      action: 'create_ga4_config_tag',
      group: 'tags',
      required: false,
      skipWhen: 'No GA4 measurement ID configured.',
      prerequisites: ['page_view_trigger'],
    },
    {
      id: 'google_ads_conversion_tag',
      order: 8,
      label: 'Google Ads Conversion Tag',
      description: 'Create a Google Ads conversion tag when conversion ID and label are available.',
      provider: 'gtm',
      resourceType: 'gtm_tag',
      action: 'create_google_ads_conversion_tag',
      group: 'tags',
      required: false,
      skipWhen: 'No Google Ads conversion ID/label configured.',
      prerequisites: ['custom_event_trigger'],
    },
    {
      id: 'container_version',
      order: 9,
      label: 'Container Version',
      description: 'Create a container version from the diagnostic workspace changes.',
      provider: 'gtm',
      resourceType: 'gtm_container_version',
      action: 'create_container_version',
      group: 'publish',
      required: true,
      skipWhen: null,
      prerequisites: ['workspace'],
    },
    {
      id: 'publish_version',
      order: 10,
      label: 'Publish Version',
      description: 'Publish the diagnostic container version (explicit opt-in only in V1).',
      provider: 'gtm',
      resourceType: 'gtm_container_publish',
      action: 'publish_container_version',
      group: 'publish',
      required: false,
      skipWhen: 'V1 default run does not publish; enable create_and_publish mode explicitly.',
      prerequisites: ['container_version'],
    },
  ].map((step) => Object.freeze(step))
);

const CREATION_DIAGNOSTIC_STEPS_BY_PROVIDER = Object.freeze({
  google_ads: GOOGLE_ADS_CREATION_DIAGNOSTIC_STEPS,
  gtm: GTM_CREATION_DIAGNOSTIC_STEPS,
});

/** Phase 0 safety + Phase 2 run contract — consumed by creation diagnostic services and API. */
const CREATION_DIAGNOSTIC_SAFETY = Object.freeze({
  RESOURCE_NAME_PREFIX: 'ZUG_DEV_TEST_',
  CONFIRM_CREATE_EXTERNAL_RESOURCES_FIELD: 'confirmCreateExternalResources',
  ADS_CAMPAIGN_STATUS: 'PAUSED',
  ADS_BUDGET_DELIVERY_METHOD: 'STANDARD',
  GTM_ACCOUNT_CREATABLE_VIA_API: false,
  SEPARATE_FROM_TEMPORAL: true,
});

/** Default run mode per provider (V1: create without publish for GTM). */
const DEFAULT_CREATION_DIAGNOSTIC_RUN_MODE_BY_PROVIDER = Object.freeze({
  google_ads: 'create_paused',
  gtm: 'create_paused',
});

/** GTM steps that require create_and_publish mode to execute. */
const GTM_PUBLISH_STEP_IDS = Object.freeze(['publish_version']);

module.exports = {
  CREATION_DIAGNOSTIC_MATRIX_VERSION,
  CREATION_DIAGNOSTIC_PROVIDERS,
  GOOGLE_ADS_CREATION_DIAGNOSTIC_STEPS,
  GTM_CREATION_DIAGNOSTIC_STEPS,
  CREATION_DIAGNOSTIC_STEPS_BY_PROVIDER,
  CREATION_DIAGNOSTIC_SAFETY,
  DEFAULT_CREATION_DIAGNOSTIC_RUN_MODE_BY_PROVIDER,
  GTM_PUBLISH_STEP_IDS,
};
