'use strict';

/**
 * Phase 10 campaign intent contract — buckets 1–3 validation codes.
 * @see mvp_implementation_plan.md → Phase 10
 */
const ADS_INTENT_CODES = Object.freeze({
  INVALID_CAMPAIGN_NAME: 'ADS_INTENT_INVALID_CAMPAIGN_NAME',
  INVALID_CAMPAIGN_CHANNEL: 'ADS_INTENT_INVALID_CAMPAIGN_CHANNEL',
  INVALID_CAMPAIGN_STATUS: 'ADS_INTENT_INVALID_CAMPAIGN_STATUS',
  INVALID_BUDGET_NAME: 'ADS_INTENT_INVALID_BUDGET_NAME',
  INVALID_BUDGET_AMOUNT: 'ADS_INTENT_INVALID_BUDGET_AMOUNT',
  INVALID_BIDDING: 'ADS_INTENT_INVALID_BIDDING',
  INVALID_NETWORK_SETTINGS: 'ADS_INTENT_INVALID_NETWORK_SETTINGS',
  INVALID_AD_GROUP_NAME: 'ADS_INTENT_INVALID_AD_GROUP_NAME',
  INVALID_AD_GROUP_TYPE: 'ADS_INTENT_INVALID_AD_GROUP_TYPE',
  INVALID_AD_GROUP_STATUS: 'ADS_INTENT_INVALID_AD_GROUP_STATUS',
  INVALID_FINAL_URL: 'ADS_INTENT_INVALID_FINAL_URL',
  RSA_HEADLINE_COUNT: 'ADS_INTENT_RSA_HEADLINE_COUNT',
  RSA_HEADLINE_LENGTH: 'ADS_INTENT_RSA_HEADLINE_LENGTH',
  RSA_DESCRIPTION_COUNT: 'ADS_INTENT_RSA_DESCRIPTION_COUNT',
  RSA_DESCRIPTION_LENGTH: 'ADS_INTENT_RSA_DESCRIPTION_LENGTH',
  RSA_DUPLICATE_TEXT: 'ADS_INTENT_RSA_DUPLICATE_TEXT',
  INVALID_KEYWORD: 'ADS_INTENT_INVALID_KEYWORD',
  INVALID_KEYWORD_MATCH_TYPE: 'ADS_INTENT_INVALID_KEYWORD_MATCH_TYPE',
  KEYWORD_INVALID_CHARS: 'ADS_INTENT_KEYWORD_INVALID_CHARS',
  KEYWORD_TOO_MANY_WORDS: 'ADS_INTENT_KEYWORD_TOO_MANY_WORDS',
  KEYWORD_SANITIZED_EMPTY: 'ADS_INTENT_KEYWORD_SANITIZED_EMPTY',
  DUPLICATE_KEYWORD: 'ADS_INTENT_DUPLICATE_KEYWORD',
  MISSING_KEYWORDS: 'ADS_INTENT_MISSING_KEYWORDS',
  MISSING_GEO_TARGET_LABELS: 'ADS_INTENT_MISSING_GEO_TARGET_LABELS',
  UNRESOLVED_GEO: 'ADS_INTENT_UNRESOLVED_GEO',
  INVALID_GEO_TARGET: 'ADS_INTENT_INVALID_GEO_TARGET',
  MISSING_CONVERSION_ACTIONS: 'ADS_INTENT_MISSING_CONVERSION_ACTIONS',
});

const CAMPAIGN_INTENT_VERSION = 1;

const CAMPAIGN_CHANNEL = Object.freeze({
  SEARCH: 'SEARCH',
});

const CAMPAIGN_STATUS = Object.freeze({
  PAUSED: 'PAUSED',
});

const AD_GROUP_TYPE = Object.freeze({
  SEARCH_STANDARD: 'SEARCH_STANDARD',
});

const BIDDING_STRATEGY = Object.freeze({
  MANUAL_CPC: 'manual_cpc',
});

const KEYWORD_MATCH_TYPE = Object.freeze({
  PHRASE: 'PHRASE',
  EXACT: 'EXACT',
  BROAD: 'BROAD',
});

const ALLOWED_KEYWORD_MATCH_TYPES = Object.freeze([
  KEYWORD_MATCH_TYPE.PHRASE,
  KEYWORD_MATCH_TYPE.EXACT,
  KEYWORD_MATCH_TYPE.BROAD,
]);

/** Google Ads minimum daily budget (micros) — V1 floor for validation. */
const MIN_DAILY_BUDGET_MICROS = 1_000_000;

const DEFAULT_DAILY_BUDGET_MICROS = 10_000_000;

const MAX_CAMPAIGN_NAME_CHARS = 255;
const MAX_AD_GROUP_NAME_CHARS = 255;
const MAX_BUDGET_NAME_CHARS = 255;
const MAX_KEYWORD_TEXT_CHARS = 80;
const MAX_KEYWORD_WORDS = 10;

const RSA_MIN_HEADLINES = 3;
const RSA_MAX_HEADLINES = 15;
const RSA_MIN_DESCRIPTIONS = 2;
const RSA_MAX_DESCRIPTIONS = 4;
const RSA_HEADLINE_MAX_CHARS = 30;
const RSA_DESCRIPTION_MAX_CHARS = 90;

const DEFAULT_NETWORK_SETTINGS = Object.freeze({
  targetGoogleSearch: true,
  targetSearchNetwork: true,
  targetContentNetwork: false,
});

/** Maps stable intent validation codes to Phase 10 validation buckets. */
const ADS_INTENT_VALIDATION_BUCKETS = Object.freeze({
  [ADS_INTENT_CODES.INVALID_CAMPAIGN_NAME]: 'campaign',
  [ADS_INTENT_CODES.INVALID_CAMPAIGN_CHANNEL]: 'campaign',
  [ADS_INTENT_CODES.INVALID_CAMPAIGN_STATUS]: 'campaign',
  [ADS_INTENT_CODES.INVALID_BUDGET_NAME]: 'campaign',
  [ADS_INTENT_CODES.INVALID_BUDGET_AMOUNT]: 'campaign',
  [ADS_INTENT_CODES.INVALID_BIDDING]: 'campaign',
  [ADS_INTENT_CODES.INVALID_NETWORK_SETTINGS]: 'campaign',
  [ADS_INTENT_CODES.INVALID_AD_GROUP_NAME]: 'ad_group',
  [ADS_INTENT_CODES.INVALID_AD_GROUP_TYPE]: 'ad_group',
  [ADS_INTENT_CODES.INVALID_AD_GROUP_STATUS]: 'ad_group',
  [ADS_INTENT_CODES.INVALID_FINAL_URL]: 'ad',
  [ADS_INTENT_CODES.RSA_HEADLINE_COUNT]: 'ad',
  [ADS_INTENT_CODES.RSA_HEADLINE_LENGTH]: 'ad',
  [ADS_INTENT_CODES.RSA_DESCRIPTION_COUNT]: 'ad',
  [ADS_INTENT_CODES.RSA_DESCRIPTION_LENGTH]: 'ad',
  [ADS_INTENT_CODES.RSA_DUPLICATE_TEXT]: 'ad',
  [ADS_INTENT_CODES.INVALID_KEYWORD]: 'keywords',
  [ADS_INTENT_CODES.INVALID_KEYWORD_MATCH_TYPE]: 'keywords',
  [ADS_INTENT_CODES.KEYWORD_INVALID_CHARS]: 'keywords',
  [ADS_INTENT_CODES.KEYWORD_TOO_MANY_WORDS]: 'keywords',
  [ADS_INTENT_CODES.KEYWORD_SANITIZED_EMPTY]: 'keywords',
  [ADS_INTENT_CODES.DUPLICATE_KEYWORD]: 'keywords',
  [ADS_INTENT_CODES.MISSING_KEYWORDS]: 'keywords',
  [ADS_INTENT_CODES.MISSING_GEO_TARGET_LABELS]: 'geo',
  [ADS_INTENT_CODES.UNRESOLVED_GEO]: 'geo',
  [ADS_INTENT_CODES.INVALID_GEO_TARGET]: 'geo',
  [ADS_INTENT_CODES.MISSING_CONVERSION_ACTIONS]: 'conversions',
});

module.exports = {
  ADS_INTENT_CODES,
  ADS_INTENT_VALIDATION_BUCKETS,
  CAMPAIGN_INTENT_VERSION,
  CAMPAIGN_CHANNEL,
  CAMPAIGN_STATUS,
  AD_GROUP_TYPE,
  BIDDING_STRATEGY,
  KEYWORD_MATCH_TYPE,
  ALLOWED_KEYWORD_MATCH_TYPES,
  MIN_DAILY_BUDGET_MICROS,
  DEFAULT_DAILY_BUDGET_MICROS,
  MAX_CAMPAIGN_NAME_CHARS,
  MAX_AD_GROUP_NAME_CHARS,
  MAX_BUDGET_NAME_CHARS,
  MAX_KEYWORD_TEXT_CHARS,
  MAX_KEYWORD_WORDS,
  RSA_MIN_HEADLINES,
  RSA_MAX_HEADLINES,
  RSA_MIN_DESCRIPTIONS,
  RSA_MAX_DESCRIPTIONS,
  RSA_HEADLINE_MAX_CHARS,
  RSA_DESCRIPTION_MAX_CHARS,
  DEFAULT_NETWORK_SETTINGS,
};
