'use strict';

/**
 * Stable codes for BusinessContext Ads readiness validation (Phase 4).
 * @see mvp_implementation_plan.md → Phase 4 / Phase 10 buckets 1–3
 */
const ADS_READINESS_CODES = Object.freeze({
  MISSING_WEBSITE_URL: 'ADS_READINESS_MISSING_WEBSITE_URL',
  INVALID_WEBSITE_URL: 'ADS_READINESS_INVALID_WEBSITE_URL',
  MISSING_BUSINESS_NAME: 'ADS_READINESS_MISSING_BUSINESS_NAME',
  MISSING_SERVICES: 'ADS_READINESS_MISSING_SERVICES',
  MISSING_SERVICE_AREAS: 'ADS_READINESS_MISSING_SERVICE_AREAS',
  MISSING_GOALS: 'ADS_READINESS_MISSING_GOALS',
  UNSUPPORTED_GOAL: 'ADS_READINESS_UNSUPPORTED_GOAL',
});

module.exports = {
  ADS_READINESS_CODES,
};
